-- Power BI DAX measures - Physical PG Inventory dashboard
-- Create these from Power BI Desktop: Modeling -> New measure

Total PGs = DISTINCTCOUNT('Physical_PG_Summary_Latest'[PGKey])

Total Objects = COUNTROWS('Physical_PG_Object_Detail_Latest')

-- Working version when IsPaused is imported as TRUE/FALSE boolean.
Paused PGs =
CALCULATE(
    DISTINCTCOUNT('Physical_PG_Summary_Latest'[PGKey]),
    'Physical_PG_Summary_Latest'[IsPaused] = TRUE()
)

-- Treat only pure success as healthy.
-- Success with warning is counted as a problem.
Problem PGs =
CALCULATE(
    DISTINCTCOUNT('Physical_PG_Summary_Latest'[PGKey]),
    FILTER(
        'Physical_PG_Summary_Latest',
        NOT (
            LOWER(TRIM('Physical_PG_Summary_Latest'[LastRunStatus])) IN {
                "ksuccess",
                "success",
                "succeeded"
            }
        )
    )
)
