-- Power BI DAX measures - Cohesity Protection Dashboard
-- Target Power BI table names:
--   PG_Summary
--   Object_Detail
--   Path_Detail
--   Exceptions
--   Run_Metadata

Active Clusters =
DISTINCTCOUNT(PG_Summary[ClusterId])

Active PGs =
DISTINCTCOUNT(PG_Summary[ProtectionGroupId])

Protected Objects =
SUM(PG_Summary[ObjectCount])

Objects With Exclusions =
CALCULATE(
    DISTINCTCOUNT(Object_Detail[ObjectId]),
    Object_Detail[HasObjectExclusions] = TRUE()
)

PGs With Global Exclusions =
CALCULATE(
    DISTINCTCOUNT(PG_Summary[ProtectionGroupId]),
    PG_Summary[GlobalExcludePathCount] > 0
)

PGs With Object Exclusions =
CALCULATE(
    DISTINCTCOUNT(PG_Summary[ProtectionGroupId]),
    PG_Summary[ObjectExcludePathCount] > 0
)

Successful Backups in Last 24h =
CALCULATE(
    DISTINCTCOUNT(PG_Summary[ProtectionGroupId]),
    PG_Summary[LastSuccessfulBackupAgeHours] <= 24
)

Backup Success 24h % =
DIVIDE(
    [Successful Backups in Last 24h],
    [Active PGs]
)

PGs Stale Over 24h =
CALCULATE(
    DISTINCTCOUNT(PG_Summary[ProtectionGroupId]),
    PG_Summary[LastSuccessfulBackupAgeHours] > 24
)

PGs Stale Over 48h =
CALCULATE(
    DISTINCTCOUNT(PG_Summary[ProtectionGroupId]),
    PG_Summary[LastSuccessfulBackupAgeHours] > 48
)

Paused PGs =
CALCULATE(
    DISTINCTCOUNT(PG_Summary[ProtectionGroupId]),
    PG_Summary[IsPaused] = TRUE()
)

Exception Count =
COUNTROWS(Exceptions)

Critical Exceptions =
CALCULATE(
    COUNTROWS(Exceptions),
    Exceptions[Severity] = "Critical"
)

High Exceptions =
CALCULATE(
    COUNTROWS(Exceptions),
    Exceptions[Severity] = "High"
)

Medium Exceptions =
CALCULATE(
    COUNTROWS(Exceptions),
    Exceptions[Severity] = "Medium"
)

PGs by Object Count =
SUM(PG_Summary[ObjectCount])

Included Path Rows =
COUNTROWS(Path_Detail)

Excluded Path Rows =
CALCULATE(
    COUNTROWS(Path_Detail),
    NOT(ISBLANK(Path_Detail[ExcludedPath]))
)
