-- Power BI DAX measures - Physical PG Inventory dashboard
-- Create these from Power BI Desktop: Modeling -> New measure

Total PGs = DISTINCTCOUNT('Physical_PG_Summary_Latest'[PGKey])

Total Objects = COUNTROWS('Physical_PG_Object_Detail_Latest')

-- Handles IsPaused imported as text, boolean-like text, or numeric text.
Paused PGs =
VAR Result =
    CALCULATE(
        DISTINCTCOUNT('Physical_PG_Summary_Latest'[PGKey]),
        FILTER(
            'Physical_PG_Summary_Latest',
            LOWER(TRIM("" & 'Physical_PG_Summary_Latest'[IsPaused])) IN {
                "true",
                "1",
                "yes"
            }
        )
    )
RETURN
    COALESCE(Result, 0)

-- Treat only pure success as healthy.
-- Success with warning is counted as a problem.
Problem PGs =
CALCULATE(
    DISTINCTCOUNT('Physical_PG_Summary_Latest'[PGKey]),
    FILTER(
        'Physical_PG_Summary_Latest',
        NOT (
            LOWER(TRIM('Physical_PG_Summary_Latest'[LastRunStatus])) IN {
                "ksuccess",
                "success",
                "succeeded"
            }
        )
    )
)
